### ISSUE TITLE
[BUG] Advanced inserter destroys carts cointaining wooden crates or any barrels

### ISSUE THREAD

**Issue by Hawk777** [Pabilo8/ImmersiveIntelligence#104]
**Describe the bug**
The advanced inserter is supposed to take crates or barrels out of minecarts, leaving the empty carts behind. This works fine for steel crates and reinforced crates. However, for carts containing wooden crates, wooden barrels, or metal barrels, the cart is also destroyed.

**To Reproduce**
1. Place some track.
2. Two squares away from the track, place an inserter with arrows pointing away from the track.
3. Two squares away from the inserter, put a destination inventory.
4. Craft a minecart with wooden crate.
5. Place the minecart on the track where the inserter can reach it.
6. Send a packet to the inserter with `b` set to true, allowing it to take blocks out of carts.

**Expected behavior**
The inserter should move the crate to the destination inventory while leaving an empty cart on the track.

**Environment**
 - OS: Linux
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2854
 - Immersive Intelligence version: 0.1.1
 - Immersive Engineering version: 0.12-98

**Comment by Pabilo8** [comment]
Fixed in #25, as a part of the inserter rework.
