### ISSUE TITLE
[BUG] Packer deletes Items when q < 64

### ISSUE THREAD

**Issue by murban-git** [Pabilo8/ImmersiveIntelligence#114]
**Describe the bug**
When you pack items in packer and the variable q is < 64, it packs the number of items in the package, but the inventory slot of the packer is empty, there where 64 items in the slot, then there was nothing

**To Reproduce**
1. Build Packer
2. Fill all slots with 64 Items
3. Configure with "Data Input Machine" (c=1,m=0,q=16,i=false) [q and i should be default]
4. chuck an valid storage Container in it (the tiny ones from the mod)

**Expected behavior**
16 Items in Package (thats ok)
48 Items in first slot in packer (thats empty)

**Environment**
 - OS: Windows
 - Minecraft version: 1.12.2
 - Forge version: latest
 - Immersive Intelligence version: latest
 - Immersive Engineering version: latest
 
 I had a clear Test environment, only these two mods wher in it.

**Comment by Pabilo8** [comment]
Fixed as a part of the Packer rework in 0.2.1
