### ISSUE TITLE
[BUG] Tripmines cause a stackoverflow exception when looked at

### ISSUE THREAD

**Issue by Cactus-man** [Pabilo8/ImmersiveIntelligence#121]
**Describe the bug**
I was experimenting with some mods when I placed down a tripmine. Almost instantly my game crashed. It shut down the internal server and exited.

**To Reproduce**
1. Place a tripmine
2. Look at it
3. Profit.

**Expected behavior**
The game does not crash when I look at the block?

**Logs**
[crash-2021-05-09_11.44.32-client.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/6447255/crash-2021-05-09_11.44.32-client.txt)

**Environment**
 - OS: "Microsoft Windows 10 Pro" Version is 10.0.19042 Build 19042
 - Minecraft version: Java Edition, 1.12
 - Forge version: Forge 14.23.5.2855
 - Immersive Intelligence version: https://www.curseforge.com/minecraft/mc-mods/immersive-intelligence/files/3298578

 - Immersive Engineering version: https://www.curseforge.com/minecraft/mc-mods/immersive-engineering/files/2974106
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.
Its in html format so I recommend changing its extension back to .html for ease of reading
GitHub wouldn't let me upload it as a html file :/
[modlist.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/6447270/modlist.txt)

**Comment by TenTonSkeleton** [comment]
I have that same issue, though that version is still in alpha, so I think that the trip mine is still a work in progress.

**Comment by Pabilo8** [comment]
Fixed in 0.2.1
