### ISSUE TITLE
[BUG] [Server] Server thread/INFO [immersiveintelligence]: false

### ISSUE THREAD

**Issue by 8qBITs** [Pabilo8/ImmersiveIntelligence#129]
**Describe the bug**
A clear description of what the bug is.

**To Reproduce**
Happens on its own in MC Eternal
keeps spamming

**Expected behavior**
Clean console

**Screenshots or GIFs**
https://i.imgur.com/HDkQYjg.png

**Logs**
No crashes

**Environment**
 - OS: Debian 10
 - Minecraft version: 1.12
 - Forge version: Latest
 - Immersive Intelligence version: Latest
 - Immersive Engineering version: Latest
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.

Modpack MC Eternal

**Comment by blackdragon2447** [comment]
that is just a debug feature that was unintentionally left in, it should be fixed in the next update.

**Comment by Pabilo8** [comment]
Fixed in 0.2.1
