### ISSUE TITLE
[Crash] Sent to desktop when I fired a gun

### ISSUE THREAD

**Issue by Asrialthe6th** [Pabilo8/ImmersiveIntelligence#138]
I Crash to desktop when I fire a machine gun or submachine gun, I hear one shot fire off and my screen for a split second shows a white screen with a circle in the top right corner like a aiming reticule. when I load back into the game I find 4 bullet casings in my hotbar.

**To Reproduce**
load a new creative world
grab a machine gun or submachine gun from creative menu
grab ammo from the creative menu
reload
right click
and that's when I crash to desktop

**Expected behavior**
the submachine gun or machine gun to fire

**Logs**
Add game logs (logs/latest.log and crash log (if exists) ).
[crash-2022-01-04_22.22.05-client.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/7812022/crash-2022-01-04_22.22.05-client.txt)

**Environment**
 - OS: windows 10
 - Minecraft version: 1.12.2
 - Forge version:  1.12.2-forge-14.23.5.2855
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version:0.12-98

OTHER MODS:
-albedo
-code chicken lib
-CTM
-engineers doors
-immersive energy
-immersive petroleum
-jei
-journey map
-immersive technology
-not enough items
-pam's brew craft
-pam's harvest craft
-optifine
-the one probe

**Comment by Pabilo8** [comment]
This was caused by Albedo (the colored lighting mod). II is compatible only with albedo 0.1.3 or older, due to IE having that version in its dependencies.
To fix you issue, use [this version of albedo](https://www.curseforge.com/minecraft/mc-mods/albedo/files/2486523) instead.
