### ISSUE TITLE
Ammunition workshop does not accept casings

### ISSUE THREAD

**Issue by danielJin100** [Pabilo8/ImmersiveIntelligence#143]
**Describe the bug**
When you try to place casings in the corresponding slot in the ammunition workshop, the casings don't go in the slot.

**To Reproduce**
1. Build the ammunition workshop
2. Place in a casing of any type in the second slot
3. Casings don't fit into the slot

**Expected behavior**
The casings go in the slot and the process starts.

**Screenshots or GIFs**
![2022-01-08_08 52 25](https://user-images.githubusercontent.com/75294070/148652945-448df6a7-4804-48fb-b41c-ce1c26897684.png)

**Environment**
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2854
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version: 012-98
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.
"energyconverters_1.12.2-1.3.7.30.jar"
"environmentaltech-1.12.2-2.0.20.1.jar"
"Immersive+Energy-1.12.2-0.5.5.jar"
"ImmersiveEngineering-0.12-98.jar"
"immersiveintelligence-0.2.1.jar"
"immersivepetroleum-1.12.2-1.1.9.jar"
"industrialcraft-2-2.8.221-ex112.jar"
"jei_1.12.2-4.16.1.301.jar"
"LibVulpes-1.12.2-0.4.2-75-universal.jar"
"MCTImmersiveTechnology-1.12.2-1.9.95.jar"
"Mekanism-1.12.2-9.8.3.390.jar"
"MekanismGenerators-1.12.2-9.8.3.390.jar"
"MekanismTools-1.12.2-9.8.3.390.jar"
"NuclearCraft-2o.5.5-1.12.2.jar"
"OptiFine_1.12.2_HD_U_G5.jar"
"QMD-1.0.3-1.12.2.jar"
"RedstoneFlux-1.12-2.1.1.1-universal.jar"
"theoneprobe-1.12-1.4.28.jar"
"ThermalFoundation-1.12.2-2.6.7.1-universal.jar"
"valkyrielib-1.12.2-2.0.20.1.jar"
"AdvancedRocketry-1.12.2-1.7.0-235-universal.jar"
"appliedenergistics2-rv6-stable-7.jar"
"BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar"
"CoFHCore-1.12.2-4.6.6.1-universal.jar"
"CoFHWorld-1.12.2-1.4.0.1-universal.jar"
"CraftTweaker2-1.12-4.1.20.662.jar"
"CTM-MC1.12.2-1.0.1.30.jar"

**Comment by Pabilo8** [comment]
Already fixed in 9e79168e088d8e2938f649dadc76e03bf7c61a20
