### ISSUE TITLE
[BUG] crash on startup

### ISSUE THREAD

**Issue by border999** [Pabilo8/ImmersiveIntelligence#145]
**Describe the bug**
See title.

**To Reproduce**
1. Start the game.
2. Unknown variables

**Logs**
Add game logs (logs/latest.log and crash log (if exists) ). 
[crash-2022-01-09_09.48.03-client.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/7835797/crash-2022-01-09_09.48.03-client.txt)

**Environment**
 - OS: Windows 11
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2855
 - Immersive Intelligence version: v0.2.1
 - Immersive Engineering version: 0.12-98

**Comment by thiago1255** [comment]
i have the same issue with my minecraft. "There was a severe problem during mod loading that has caused the game to fail" 
But, i use forge "1.12.2-14.23.5.2860" OS "Linux mint 20.2" and Java "1.8.0_311"
[crash-2022-01-10_02.55.33-client.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/7836879/crash-2022-01-10_02.55.33-client.txt)
[latest.log](https://github.com/Pabilo8/ImmersiveIntelligence/files/7836881/latest.log)

**Comment by Pabilo8** [comment]
Please remove the mod's config when updating to 0.2.1
It is mentioned in the curseforge changelog at the beginning of it.
![image](https://user-images.githubusercontent.com/34772833/149658448-860ddc67-3052-4c32-9c74-cf9eea8c53c4.png)
