### ISSUE TITLE
[BUG] Zinc and platinum ores/ingots smelting bug 

### ISSUE THREAD

**Issue by komapro** [Pabilo8/ImmersiveIntelligence#159]
**Describe the bug**
Zinc and platinum ore do not smelt into their respective ingots.
Might have to do something with #139 

**To Reproduce**
1. Try to smelt zinc or platinum ore.
2. Wait for it to smelt.
3. Notice it producing either nothing or the wrong ingot.

**Expected behavior**
Ores would smelt into correct ingots.

**Screenshots or GIFs**
https://user-images.githubusercontent.com/87088939/153882294-ce345faf-1e40-4f1a-a1fc-cd2a2cffa632.mp4

**Logs**
[latest.log](https://github.com/Pabilo8/ImmersiveIntelligence/files/8061455/latest.log)

**Environment**
 - OS: W10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2588
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version: 0.12-98
 - Other mods:
 - Alternating Flux 0.12.2-2
 - Engineers Doors 0.9.1
 - Immersive Energy 0.5.5
 - Immersive Petroleum 1.1.10
 - Immersive Technology 1.9.99
 - JourneyMap 1.12.2-5.7.1
 - Just Enough Items 4.15.0.296
 - The One Probe 1.12-1.4.28
 - Portable Drill 1.2.1
 - Questionably Immersive 0.1.0
 - TOP Addons 1.12.2-1.13.0

**Comment by Lordician** [comment]
Investigated and possible source found:
On [line 802 in IIRecipes](https://github.com/Pabilo8/ImmersiveIntelligence/blob/fb18ad30d300af0306a2a98363eca29a25e3c513/src/main/java/pl/pabilo8/immersiveintelligence/common/IIRecipes.java#L802) the code creates an ItemStack with 2 parameters, but this fills in the meta number as the amount. All it needs is another parameter (",1") inbetween the current two.
Example:
`new ItemStack(IIContent.blockOre, IIBlockTypes_Ore.ZINC.getMeta())` [OLD]
`new ItemStack(IIContent.blockOre, 1, IIBlockTypes_Ore.ZINC.getMeta())` [NEW]
This mistake is repeated quite a few times in IIRecipes, so there are more recipes in there that are currently broken.

This problem causes multiple issues, one is not showing the right recipe in JEI (different ore required for the ingot), not showing the oreblock required for the recipe in JEI and of course the ingots not being able to be made using a normal furnace.
