### ISSUE TITLE
[BUG] Ammunition Workshop broken?

### ISSUE THREAD

**Issue by sirNacati** [Pabilo8/ImmersiveIntelligence#162]
**Describe the bug**
Can't craft anything with the ammunition workshop, I can put the "Cores" on the first slot but nothing else on the second slot...

**Environment**
 - OS: Win 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2855
 - Immersive Intelligence version: 0.12-98
 - Immersive Engineering version: 0.2.1.
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.

**Comment by kappa-maintainer** [comment]
The second slot need shells filled with gunpowder, you should build a filler multiblock to do this first

**Comment by sirNacati** [comment]
Ah I see, you are quite right sir, apologies for my incompetence.
You wouldn't by any chance also how to now load said bullets into the magazine? I'm having trouble getting the buggers in... xD

**Comment by kappa-maintainer** [comment]
> Ah I see, you are quite right sir, apologies for my incompetence.
> You wouldn't by any chance also how to now load said bullets into the magazine? I'm having trouble getting the buggers in... xD

You need a packer multiblock to load them in magazines.

**Comment by sirNacati** [comment]
Excellent!! I will now be able to purge those rapscallions from my lands.
Once gain many thanks good sir.
