### ISSUE TITLE
[BUG] Client crashes when closing engineers manual on server

### ISSUE THREAD

**Issue by Unadvised55** [Pabilo8/ImmersiveIntelligence#168]
**Describe the bug**
Closing the Engineers Manual crashes the client and gives the error: "A fatal error has occured; Connection terminated"

**To Reproduce**
1. Open the Engineers Manual on a server
2. Close the Engineers Manual on a server

**Expected behavior**
To exit the Engineers Manual GUI and continue on with my business.

**Logs**
I'll have to grab these later

**Environment**
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2859
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version: 0.12-98

**Comment by Harakhti** [comment]
Similar issue on Forge 14.23.5.2860 running on Oracle Java 8u312, attached the error message:
[servererror.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/8471766/servererror.txt)

**Comment by LubieKakao1212** [comment]
a PR with a fix for this already exists

**Comment by LeonMonkeygamer** [comment]
> a PR with a fix for this already exists

Whats is a PR and how can i fix this bug?

**Comment by Pabilo8** [comment]
Fixed by 0ae61bb8d159bebac6075a35a2834c52e923d94d.
