### ISSUE TITLE
[BUG]howitzers model error

### ISSUE THREAD

**Issue by quantumfox-1** [Pabilo8/ImmersiveIntelligence#186]
**Describe the bug**
A clear description of what the bug is.

**To Reproduce**
1. Place a block
2. Wait for the block to do things
3. See the block doing its things
4. Actually it doesn't

**Expected behavior**
The ramrod overextended.

**Screenshots or GIFs**
Add screenshots of animated GIFs (even better) of the problem (if it is a visual glitch).

**Logs**
Hoping to get fixed
**Environment**
 - OS:Windows 10 
 - Minecraft version:1.12.2
 - Forge version:14.23.5.2860
 - Immersive Intelligence version:0.12-98
 - Immersive Engineering version:0.2.1
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.

https://user-images.githubusercontent.com/104590682/165880023-25636c1a-14b3-45ee-aa37-df1eec657cd2.mp4

!

**Comment by Pabilo8** [comment]
The howitzer model and rendering code was updated. Fixed by bccb134b0581b99048cc3eeca54feac265166ba4.
