### ISSUE TITLE
[BUG} How do you place emplacements

### ISSUE THREAD

**Issue by GtTvGaming** [Pabilo8/ImmersiveIntelligence#187]
I don't know how to place things like the machine gun nest

**Comment by quantumfox-1** [comment]
Emplacement Weapons?

**Comment by GtTvGaming** [comment]
yes

**Comment by quantumfox-1** [comment]
To build a good Emplacemen,employ Engineer's Electric Wrench Right click on it

**Comment by Pabilo8** [comment]
Manual description for emplacements will be improved (as part of a general manual works).
