### ISSUE TITLE
[BUG] Disconnect from Server when open Immersive Enge

### ISSUE THREAD

**Issue by LeonMonkeygamer** [Pabilo8/ImmersiveIntelligence#190]
You get kicked from the server when open the Immersive Engineering book
My modpack i used it is: https://www.curseforge.com/minecraft/modpacks/zombie-revolution

Server Log:
https://gnomebot.dev/paste/974361587613855844

**Comment by HiiroSaya** [comment]
Same

**Comment by zyxkad** [comment]
Same @Pabilo8

**Comment by zyxkad** [comment]
This should fixed by <https://github.com/Pabilo8/ImmersiveIntelligence/commit/0ae61bb8d159bebac6075a35a2834c52e923d94d>
Can you create a new release? Then we needn't download the source and build it.

**Comment by zyxkad** [comment]
This issue should merge to #136

**Comment by kappa-maintainer** [comment]
> This should fixed by <https://github.com/Pabilo8/ImmersiveIntelligence/commit/0ae61bb8d159bebac6075a35a2834c52e923d94d>
> Can you create a new release? Then we needn't download the source and build it.

You can find a test build in Discord

**Comment by Faolon12** [comment]
when will this release? would love to update a modpack i have for my server.

**Comment by Pabilo8** [comment]
Fixed by 0ae61bb.
