### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by euanPC** [Pabilo8/ImmersiveIntelligence#196]
**Describe the bug**
Game crashes when packing smg bullets into smg cartridge
**To Reproduce**
place smg ammo (uranium) into packer
set packer to pack smg cartridge with item
throw smg cart on conveyer

**Expected behavior**
cartridge to be loaded
**Screenshots or GIFs**
Add screenshots of animated GIFs (even better) of the problem (if it is a visual glitch).
![image](https://user-images.githubusercontent.com/40900940/174658548-39af613a-5db4-4d30-bc4c-e81831fb5f5f.png)
![image](https://user-images.githubusercontent.com/40900940/174658596-c256a7dc-8861-4e86-9e79-65d1d5223f6e.png)

**Logs**
Add game logs (logs/latest.log and crash log (if exists) ).

[crash-2022-06-20_11.33.48-client.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/8942879/crash-2022-06-20_11.33.48-client.txt)
022-06-20_11.33.48-client.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/8942875/crash-2022-06-20_11.33.48-client.txt)

**Environment**
 - OS:Win10
 - Minecraft version:1.12
 - Forge version:14.23.5.2860
 - Immersive Intelligence version:0.2.1
 - Immersive Engineering version:0.12-98
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.

**Comment by Pabilo8** [comment]
Crash was fixed during the general packer overhaul/rework.

Also , your setup wouldn't work: the tasks section is for item filters (types of items packer should use and their amount per one packing action).

Change the magazine to the bullet item you put into the inventory or make it blank (meaning no filter)
