### ISSUE TITLE
[BUG] cannot use hammer on concrete 

### ISSUE THREAD

**Issue by Hawk91101** [Pabilo8/ImmersiveIntelligence#200]
**Describe the bug**
so I was trying to make the howitzer cannon, and some how when I tried to use the hammer on the concrete block that sticks out the hammer didn't move and nothing happened, the same thing happened when I was trying to spawn the emplacement

**Environment**
 - OS: Mac 12.4 Monterey
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2859
 - Immersive Intelligence version:0.21
 - Immersive Engineering version:0.12-98
 - other mods installed: (see attached photo)
<img width="1440" alt="截屏2022-07-14 20 23 12" src="https://user-images.githubusercontent.com/109287630/178981452-d6b23d45-3319-4eb8-a4b4-df137bf94539.png">
)

**Comment by MrDiamondDog** [comment]
Did you hit the side of it? I'm pretty sure you have to hit the top. It worked fine for me with similar mods.

**Comment by Hawk91101** [comment]
> Did you hit the side of it? I'm pretty sure you have to hit the top. It worked fine for me with similar mods.
 which hammer did you use?  because it didn't work for me on the top as well
