### ISSUE TITLE
[BUG] can't craft the light engineer armor

### ISSUE THREAD

**Issue by Endemion4589** [Pabilo8/ImmersiveIntelligence#207]
I simply can't craft the light engineer armor and so all the people on my server, plus I'm also seeing on various forum that even other people can't craft it 
![Bug](https://user-images.githubusercontent.com/68474042/182159098-88c979d7-24e3-42a7-9583-9db168b40cb1.PNG)

**Comment by Pabilo8** [comment]
Fixed in 9682e8baa3009deb1922f1ab3f0db84a13cb1813.
