### ISSUE TITLE
Packer & Unpacker

### ISSUE THREAD

**Issue by Pabilo8** [Pabilo8/ImmersiveIntelligence#23]
Two machines, first will pack items from its inventory into a crate (or any other container [MG/SMG/REV MAGAZINES] , the second will do the opposite.
There will be two variants, one will handle minecarts with containers, and the other would have a standard container item input and output.

Work:
@Choroman 
 - [x] Express your anger at @Pabilo8, because he's giving you more work
 - [x] Express your anger at SMP Toolbox, because its a piece of shite
 - [x] Make the packer model (standard)
 - [x] Convert the packer model into the minecart handling one
 - [x] Make the unpacker model (standard)
 - [x] Convert the unpacker model into the minecart handling one

@Pabilo8 
 - [x] Express your anger at @Choroman, because he's not working
 - [x] Try to calm @Choroman while he's expressing his anger at SMP Toolbox (?Help him)
 - [x] Add the models
 - [x] Basic TE & Multiblock
 - [x] Basic rendering
 - [x] Make TE functional
 - [ ] Finish rendering

Both
 - [ ] Profit

Design Docs:
![packer_unpacker](https://user-images.githubusercontent.com/34772833/68998100-25384d80-08ae-11ea-9928-d1f7420fc933.jpg)

**Comment by Pabilo8** [comment]
Packer and unpacker were merged into one machine in 0.2.1
Pozdrowienia dla ciebie, Choromanie, ty stary draniu ^^

**Comment by Choroman** [comment]
Do kierownictwa nadzoru zarządu rady szefostwa

Ja rozumiem draniu, ale że stary?

Z pozdrowieniami

Drań Choroman

wt., 4 sty 2022, 09:45 użytkownik Paweł Godlewski ***@***.***>
napisał:
