### ISSUE TITLE
Unable to craft Reinforced crates in survival

### ISSUE THREAD

**Issue by Royal-Jelly** [Pabilo8/ImmersiveIntelligence#30]
The shapeless recipe for the alternative crates in Immersive intelligence might be preventing the crafting of the reinforced crates needed for the Precision Assembler Multiblock

![2020-04-30_00 25 13](https://user-images.githubusercontent.com/14046681/80672456-cdb42580-8a7a-11ea-89f7-32089cf15574.png)
Shaped Recipe is still able to be viewed by player, looks all good here but . . .

![2020-04-30_00 25 22](https://user-images.githubusercontent.com/14046681/80672457-ce4cbc00-8a7a-11ea-9fb4-1decd0ce786e.png)
Something is definitely bust, hopefully I'm first to breeze past this little bug

Environment Details
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2847
 - Immersive Intelligence version: 0.12.92-559
 - Immersive Engineering version: 0.1.0

Other IE addons installed in environment:
 - Immersive Petroleum version: 1.1.8
 - Immersive Technology version: 1.7.58

Also I've been keeping up with the mod since late December last year, many thanks for the release and good luck to you and your team ~

**Comment by Pabilo8** [comment]
Thanks for the report, will be fixed in the next release... and yes I'm aware you're one of the first people that have seen the mod and gave a star on GitHub ^^. Not going to forget that, someday I'll make a reference to you in one of the advancements, I did that for some people already.

**Comment by copygirl** [comment]
There is an issue with the fix where it would match recipes when the first non-empty stack is a crate, but there could still be other stacks in the item grid, voiding them as a result. I would recommend to just replace this with simple recipes - they can then also be displayed by JEI.

The required tool to harvest, sounds, hitboxes and break particles are all off as well, so I opted to removing the recipes and hide the items with CraftTweaker:
```zs
recipes.removeByRecipeName("immersiveintelligence:small_crate_wooden");
recipes.removeByRecipeName("immersiveintelligence:small_crate_metal");
JEI.hide(<immersiveintelligence:small_crate:*>);
```
