### ISSUE TITLE
[Feature Request] Standing in any acid will damage any entity in it.

### ISSUE THREAD

**Issue by Carvercarver1** [Pabilo8/ImmersiveIntelligence#34]
Title.

Also, probably, some configuration for armors which are resistent to acid, but instead armor gets damaged at rapid pace. 
Also, any item or just some "weak" items which are thrown into acid will get dissloved/destroyed due to it's highly corrosive effect.

Same would apply to the chemical bath.

**Comment by kingcavespider1** [comment]
I added this in a fork and sent a pull request #54

**Comment by Pabilo8** [comment]
Closed by #54
