### ISSUE TITLE
[BUG] Scanner conveyor belt manual recipe conveyor is purple

### ISSUE THREAD

**Issue by Carvercarver1** [Pabilo8/ImmersiveIntelligence#36]
Title, already described in discord

**Comment by Carvercarver1** [comment]
Update: it seems to be present on all schematics involving conveyors

**Comment by lag42** [comment]
on a related note it's also impossible to distinguish which ones should be covered conveyor belts(and any conveyor belt will tick off either covered or uncovered conveyor belts in the material list)
