### ISSUE TITLE
[BUG] ammunition factory accepts non-valid cores, creating bullets that crash the game

### ISSUE THREAD

**Issue by lag42** [Pabilo8/ImmersiveIntelligence#39]
**Describe the bug**
the howitzer crashes the game upon accepting an artillery shell that was customized in a certain way
EDIT EDIT: thanks to you telling me what the slots are in the ammunition factory i figured out the problem, i was using invalid items for the core
**To Reproduce**
1. build a ammunition factory
2. put gunpowder in the middle slot, anything in the other middle slot
3. toss an empty artillery shell in and start the crafting process
4. build a howitzer artillery or place down a machine gun
5. load howitzer artillery with the shell you just made

**Expected behavior**
i expected the howitzer to accept the shell without crashing the game / i expected the machine gun to fire the ammunition without crashing

**Logs**
[here's the crash log neatly packed in a github gist](https://gist.github.com/lag42/d3bf943277da4c2c3b06038d0c60ca2f)

**Environment**
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2854
 - Immersive Intelligence version: 1.12.2-0.1.1
 - Immersive Engineering version: 0.12-92
 - Immersive Petroleum version: 1.12.2-1.1.9
 - Just Enough Items version: 1.12.2-4.15.0.293

**Comment by heyheyhey123243** [comment]
Sorry to re-open this but I can't find any further solution or documentation to this problem on discord or here. What is the correct preset that you need to use in the ammunition factory for the shell so it doesn't cause this crash?
