### ISSUE TITLE
[BUG] Electrical Hammer deleted in IE Charging Station.

### ISSUE THREAD

**Issue by UnlimatedStone9** [Pabilo8/ImmersiveIntelligence#51]
**Describe the bug**
Electrical hammer gets consumed in IE charging station.

**To Reproduce**
1. Place and power an IE charging station.
2. Place an electrical hammer into it.
3. *See the block doing its things*
4. Hammer goes deletus.

**Expected behavior**
The Immersive Engineering charging station to charge the electric hammer like it does with the other tools.

**Environment**
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2854
 - Immersive Intelligence version: 1.12.2-0.1.1
 - Immersive Engineering version: 0.12 - 92

**Comment by Pabilo8** [comment]
The bug can't be fixed because of no possibility on IE's side to blacklist hammer use on certain block.
If you want to charge the hammer, either use a capacitor backpack or two hoppers/inserters with a charging station.
