### ISSUE TITLE
[BUG] Right clicking item inserters doesn't open its GUI

### ISSUE THREAD

**Issue by Archilyte** [Pabilo8/ImmersiveIntelligence#52]
**Describe the bug**
Title says it all

**To Reproduce**
1. Place an inserter
2. Wait for the block to take items out of the chest into another chest
3. See the block doing its things
4. Actually it doesn't because it needs configuration
5. Try to open the GUI to configure the inserter by right-clicking it
6. GUI doesn't open

**Expected behavior**
GUI should open, or that's what I was told at the Curseforge comments

**Environment**
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2854
 - Immersive Intelligence version: 0.1.1
 - Immersive Engineering version: 0.12-92

**If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.**
i have 318 other mods installed, and getting a list of them will take a while. Just ask me if you need it tho...

**Comment by Pabilo8** [comment]
I think someone has misinformed you about how inserters work. They are a precise block that can pick the exact amount of items player wants from a container. There is info on how to use them in manual.
Basically they need power and data signal with certain variables.
Use a data input machine to send it a signal with integer 'c' - the amount of items to pick up, string 'm' - mode (add - pick up current+new, set - set exact amount)
