### ISSUE TITLE
[BUG] [Server thread/INFO] [immersiveintelligence]: false

### ISSUE THREAD

**Issue by Delta4Phoenix** [Pabilo8/ImmersiveIntelligence#57]
I have constant spam of "[Server thread/INFO] [immersiveintelligence]: false" in my log, which also causes log files to balloon in size. Is there any way to stop this?

**To Reproduce**
Play with the mod.

**Expected behavior**
No spam, that'd be nice.

**Logs**
Add game logs (logs/latest.log and crash log (if exists) ).

**Environment**
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2847
 - Immersive Intelligence version: 0.1.1
 - Immersive Engineering version: 0.12-92
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.
[modlist.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/4612794/modlist.txt)
[latest.log](https://github.com/Pabilo8/ImmersiveIntelligence/files/4612796/latest.log)

**Comment by border999** [comment]
I'm having the same issue.

**Comment by Pabilo8** [comment]
Will be fixed in the newest release

**Comment by Zafaranec** [comment]
I get again spam of this messages, unfortunately, is somehow linked with crafting table, when I took item from them, server log 10 times this message, with crafting station from Tinkers construct, 5 times when I open it, 5 times when took item from them. That's a lot of spam, especially when with huge modpack is crafting most important thing(logging of retrogen I try disable already before)

**Comment by FENG-MASTER** [comment]
I'm having the same issue now
