### ISSUE TITLE
Ammunition Factory

### ISSUE THREAD

**Issue by Pabilo8** [Pabilo8/ImmersiveIntelligence#6]
A multiblock able to produce munitions of all sort.
@Choroman:
 - [x] Model
 - [x] Modelling - Change the steel boxes into a bench with books / blueprints, add gauges on the side (maybe a button too?)
- [x] Modelling - Change the steel sheetmetal texture into something different (maybe the shiny steel texture from Electrolyzer?) (I pay extra ^^)

@Pabilo8:
- [x] Bullet additions - custom paint and bullet core visible on ItemStack (maybe custom scale depending on bullet size?)
 - [x] Multiblock
 - [x] TileEntity
 - [x] Rendering - Basic
 - [x] Recipes ~~and Crafttweaker~~
 - [x] Implementation
 - [x] Rendering (proper)

**Comment by Choroman** [comment]
Ok.
