### ISSUE TITLE
[Feature Request] Data Network display block

### ISSUE THREAD

**Issue by aaronhsmine** [Pabilo8/ImmersiveIntelligence#61]
**Category**
**Data and Electronics**
**Description**
Add some kind of display or block which can show the Value of a Variable from the Packet it last received. Would be useful for testing, for example, a howitzer control network. Or for sending messages via radio.

**Comment by Pabilo8** [comment]
The Data Debugger now stores the last packet it receives and displays it as text on HUD when being looked at.
