### ISSUE TITLE
[BUG] Electrolyzer Not Forming

### ISSUE THREAD

**Issue by therobotmenace** [Pabilo8/ImmersiveIntelligence#63]
**Describe the bug**
After placing all of the blocks for the electrolyzer, it will not form. I have tried placing the blocks in midair on their own and it still does not form.

**To Reproduce**
1. Build the multiblock structure
2. Right clicking on any of the heavy engineering blocks does not do anything.

**Expected behavior**
When forming the multiblock, I expected the structure to form when right clicking on the heavy engineering block.

**Environment**
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2854
 - Immersive Intelligence version: 0.1.1
 - Immersive Engineering version: 0.12-92

**Comment by Pabilo8** [comment]
Are you using projectors from Immersive Petroleum? If so, shift+middle click to flip the multiblock.
To form it use a hammer on the side of this block,
![image](https://user-images.githubusercontent.com/34772833/82480259-d1642680-9ad3-11ea-9456-67e34e6aa060.png)

**Comment by ByteZ1337** [comment]
I just had the same issue by using the steel blocks from thermal foundation. Maybe that's your issue? Some type of oredict support should definitely be added

**Comment by therobotmenace** [comment]
Yea that seems to be the issue. I can't build the multiblock in the current pack I'm running as Thermal Foundation has replaced all of the duplicate ingots with it's own. Oredict support would definitely be nice.
