### ISSUE TITLE
[BUG] Artillery Howitzer not forming

### ISSUE THREAD

**Issue by whatsapp2** [Pabilo8/ImmersiveIntelligence#68]
**Describe the bug**
I built the multiblock with the help of immersive petroleum projector, however the multiblock is not formed successfully. I tried to right click each of the blocks in different angles with the IE hammer and the charged ImI electric hammer, nothing happened and I keep trying without any success

**To Reproduce**
1. Use the immersive petroleum projector, build the multiblock by hand
2. Try clicking the multiblock with an electric hammer
4. The multiblock doesn't form

**Screenshots or GIFs**
(none)

**Logs**
(I can't provide a latest.log file cause Pastebin doesn't let me upload file that exceeds 512kb, also I've checked the log and it's spammed by [Client thread/INFO] [immersiveintelligence]: false)

**Environment**
 - OS: macOS Catalina Version 10.15.4
 - Minecraft version: Minecraft Forge 1.12.2
 - Forge version: 1.12.2-forge-14.23.5.2854
 - Immersive Intelligence version: 0.1.1
 - Immersive Engineering version: 0.12-98
 - Immersive petroleum 1.1.9

**Comment by Mushguys** [comment]
It doesn't look like the projector is part of the problem. I got the same problem without Immersive Petroleum, in Linux.
Probably related: the manual "required" list says ??? when it should say Reinforced Crate.

**Comment by Mushguys** [comment]
Definitely a problem with the Reinforced Crates.
I removed them temporarily and the multiblock formed correctly.

**Comment by Rayset8** [comment]
I believe this is a problem with the Immersive Petroleum projector, mirroring the Howlitzer for some reason. All i needed to do to form it was swap the redstone engineering block + steel blocks and the concrete block.

**Comment by Mushguys** [comment]
I had a similar problem without the projector, though. In fact, I didn't have Immersive Petroleum installed at all.
This might actually be two distinct issues: one with the Storage Crates, and one with the Projector.
