### ISSUE TITLE
Inserters wont work

### ISSUE THREAD

**Issue by Oaklizard-2047** [Pabilo8/ImmersiveIntelligence#69]
So I've been having problem with inserters. It seems to be not working no matter much energy i give. I tried linking it with a data cable but it says that i cant put a wire there.  

Environment:
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Immersive Intelligence version: 0.1.1
 - Immersive Engineering version: 0.12-98

Mod List :
Albedo 1.1.0
BetterFps 1.4.8
ChunkAnimator 1.2
CreativeCore 1.10.16
CTM 1.0.2.31
Engineers Decor 1.0.20
Hwlya 1.8.26-B41
Immersive Engineering 0.12-98
Immersive Intelligence 0.1.1
Immersive Posts 0.2.1
Item Physic Full 1.4.34
JEI 4.1.15.0.293
Little Tiles 1.5.0-pre199_34
Optifine 1.12.2_HD_U_F4
Phosphor 0.2.6
Railcraft 12.0.0

**Comment by Pabilo8** [comment]
Inserters work fine, though next patch will contain a code style/performance overhaul, as in #25
Are you sure you're attaching the wire to the correct spot? I tested attaching the wires with data first and last and there were no problems.

**Comment by Oaklizard-2047** [comment]
ok maybe it's just my lack of knowledge on the mod. i managed to attach a data wire to the inserter but i just dont know how to operate it. can you please tell me how to make these things work?
