### ISSUE TITLE
[BUG] Penetration damage stored by position, not block

### ISSUE THREAD

**Issue by Mushguys** [Pabilo8/ImmersiveIntelligence#73]
**Describe the bug**
Penetration damage is stored by position, not by block.
If you break a damaged block, then replace it, the new block will be damaged.
If you move a damaged block with a piston, the block will stop being damaged (but the piston head will be damaged).

**To Reproduce**
1. Damage a block (I used the machinegun)
2. Break the block.
3. Replace the block.
4. The block is damaged.

**Expected behavior**
If you break a block, the penetration damage should be removed from that position.
If you move a block, the penetration damage should move with it.
Or, the penetration damage could be stored on the block somehow.

**Screenshots or GIFs**
![2020-07-11_13 43 58](https://user-images.githubusercontent.com/67520825/87225725-90271f00-c37e-11ea-981b-f125bbd586e9.png)
![2020-07-11_13 44 03](https://user-images.githubusercontent.com/67520825/87225727-90271f00-c37e-11ea-81df-12dfa22e4013.png)
![2020-07-11_13 44 05](https://user-images.githubusercontent.com/67520825/87225728-90bfb580-c37e-11ea-996e-e747dfa05e06.png)
![2020-07-11_13 52 38](https://user-images.githubusercontent.com/67520825/87225729-90bfb580-c37e-11ea-8f40-cfe9413aae63.png)
![2020-07-11_13 52 45](https://user-images.githubusercontent.com/67520825/87225730-90bfb580-c37e-11ea-8749-44cdfedea862.png)

**Environment**
 - OS: Linux Debian 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2847
 - Immersive Intelligence version: 0.1.1
 - Immersive Engineering version: 0.12-89

**Comment by Pabilo8** [comment]
Now penetration should react to block changes and on client side keeps only 16 of them, for rendering performance.
