### ISSUE TITLE
[BUG] Assembly Scheme showing "Items Created: 0"

### ISSUE THREAD

**Issue by Mushguys** [Pabilo8/ImmersiveIntelligence#77]
**Describe the bug**
When you hover over any Assembly Scheme, the tooltip says "Items Created: 0"

**To Reproduce**
1. Hover over any Assembly Scheme.

**Expected behavior**
Assembly Scheme tooltip says "Items Created: 1", or however many items the Scheme actually creates.

**Screenshots or GIFs**
![2020-07-09_14 37 43](https://user-images.githubusercontent.com/67520825/87322925-96073680-c51d-11ea-9447-cc548937c06b.png)
![2020-07-13_15 26 52](https://user-images.githubusercontent.com/67520825/87322957-a15a6200-c51d-11ea-8ee4-4a541d4c8a0f.png)

**Environment**
 - OS: Linux Debian 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2847
 - Immersive Intelligence version: 0.1.1
 - Immersive Engineering version: 0.12-89
No other mods installed.

**Comment by Pabilo8** [comment]
That is a counter for how many items have been created using the scheme (now how many it creates, that's part of "Used to create: something x quantity"). Originally I planned a research system for better components, scraped the idea, but left a counter of created items.
