### ISSUE TITLE
[BUG] Hammering a lone Advanced Electronic Engineering Block gives a chat message

### ISSUE THREAD

**Issue by Mushguys** [Pabilo8/ImmersiveIntelligence#78]
**Describe the bug**
If you place an Advanced Electronic Engineering Block and hit it with an Engineer's Hammer (non-electric), it generates a chat message, even if the Block is not part of a machine. This is potentially misleading.

**To Reproduce**
1. Place an Advanced Electronic Engineering Block
2. Hit it with an Engineer's Hammer (non-electric)
3. Observe the chat message that appears.

**Expected behavior**
No chat message.

**Screenshots or GIFs**
![2020-07-18_14 06 01](https://user-images.githubusercontent.com/67520825/87854299-85c9cf80-c900-11ea-8073-ff0cfa64efaa.png)

**Environment**
- OS: Linux Debian 10
- Minecraft version: 1.12.2
- Forge version: 14.23.5.2847
- Immersive Intelligence version: 0.1.1
- Immersive Engineering version: 0.12-89
No other mods installed.

**Comment by Pabilo8** [comment]
fixed by 61abba40aad3c3d1379629d6c68f47ad1d642192
