### ISSUE TITLE
[Feature Request] More Craftweaker Support

### ISSUE THREAD

**Issue by Royal-Jelly** [Pabilo8/ImmersiveIntelligence#80]
Would be a great for more recipe customization options via crafttweaker for packmakers

**Comment by SnaveSutit** [comment]
I'd also love to add recipes to the precision assembler. It's an excellent way of producing advanced crafting recipes :)
(Maybe change the title of the issue to just "Craftweaker support" so people don't think you're only planning on adding it for the sawmill)
