### ISSUE TITLE
[BUG] Engineer's Manual Conveyor Belt Issue

### ISSUE THREAD

**Issue by SPYROHAWK** [Pabilo8/ImmersiveIntelligence#81]
I apologize if this isn't a perfect bug report, this is actually my first time using GitHub.

I've made multiple modpacks for fun using ImmersiveIntelligence and I have this same problem no matter what I do. In the Engineering Manual, all the ImmersiveIntelligence machines that use conveyor belts have missing textures on the belts. While this would not seem a super big issue, it seems that the belts need to be placed in the right direction. For a small machine like the packer with only 7 conveyor belts that's (in theory) 2401 combinations, but functionally much less because of common sense that conveyor belts in a line need to be placed together.

The packer was actually fine because this issue had a diagram of the belt directions: (https://github.com/Pabilo8/ImmersiveIntelligence/issues/23) but that's not the same will other machines. If I remember correctly the ammunition assembly machine has 10 conveyor belts on it, with 10000 possible combinations of directions. And since the conveyor belts have turns and whatnot, that makes it near impossible to figure out the right direction.

I'm not sure if this is a known bug or something that's due to a mod conflict, but every single modpack I've made has had the same issue.

The "proper" fix would be to fix the broken textures in the Engineer's Manual pages, and indicate the proper conveyor belt directions. I guess a "quick" fix would just be to add a line in the machine pages explaining which direction they go in, or adding a wiki onto the GitHub explaining it.

Also idk if this is relevant for your end, but the Immersive Petroleum projectors also project these machines with the broken texture conveyor belts, even when auto-building in creative mode, meaning there isn't even a workaround that way.

So uhhh... I don't really know how to end this out. But thanks for listening?

**Comment by blackdragon2447** [comment]
It is because of the fact that the manual is trying to display tile.conveyerbelt..name instead of tile.conveyerbelt.name there is a . too many in the name.
