### ISSUE TITLE
[BUG] Packer's multiblock render and IP Projection are misleading/wrong. Also, conveyors missing textures.

### ISSUE THREAD

**Issue by NightKnight97** [Pabilo8/ImmersiveIntelligence#86]
**Describe the bug**
The render for the Packer in the engineer's manual and the Immersive Petroleum projector show that the 3 conveyors on the bottom layer of the multiblock are supposed to just be regular conveyors. In actuality for the multiblock to form the bottom 3 conveyors have to be covered conveyors, directed away and past the fluid pipes above them. The mouse-over "?" tooltip next to the in manual render keyed me into this as it correctly calls for 3x covered belts.

Also of note, all conveyors rendered in manual and placed via I.P. projector are missing textures & spawn in at a fixed rotation 
![Instructed Layout](https://user-images.githubusercontent.com/73003327/96323992-4af53780-0fd4-11eb-88b8-fe9c6b8e925b.png)

![Correct layout](https://user-images.githubusercontent.com/73003327/96323998-4df02800-0fd4-11eb-99e3-4fd9963057c8.png)

![Manual Discrepancies](https://user-images.githubusercontent.com/73003327/96323305-66ab0e80-0fd1-11eb-9c92-a981a5434c5c.png)

Thank you for putting the work into this mod! love it :) 

**Environment**
 - OS: win10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2847
 - Immersive Intelligence version: 1.12.2-0.1.1
 - Immersive Engineering version: 0.12-98
Other mods:
I'm running the current version of MC Eternal as of this date as well as around 20 or mods added in.

**Comment by BrisingrAerowing** [comment]
That's an issue with IP, as it mirrors multiblocks by default and II has issues with that.

**Comment by NightKnight97** [comment]
> That's an issue with IP, as it mirrors multiblocks by default and II has issues with that.
True, though that is not the issue I brought up.
