### ISSUE TITLE
Howitzer is not forming.

### ISSUE THREAD

**Issue by DR-JFZoidberg** [Pabilo8/ImmersiveIntelligence#90]
Running MC 1.12.2, II version 1.1, and the howitzer refuses to form. I followed this [video](https://www.youtube.com/watch?v=eCwGY-Dgnzw&feature=youtu.be), and right clicked the respective tile with the engineers hammer. Then I went around the whole structure, meticulously clicking every block. 

I eventually clicked on the center block, level 2 on the side with the Advanced Electronic Engineering Block, and it prompted me with "Advanced engineering requires advanced tools... you need an Electric Hammer to build this machine!" So I charged up an Electric Hammer and still had no results.

Looking forward to this mod!

**Comment by Pabilo8** [comment]
You have to use the Engineer's Hammer (or the electric one) on the side of the concrete block that sticks out
If you built it using the IP projector, flip it, or use the dev release, available on our discord server
The message was a bug related to the radio station, it's fixed now
Thanks for interest in my mod ^^
