### ISSUE TITLE
Vein size of zero crashes with a NullPointerException

### ISSUE THREAD

**Issue by AechtRob** [Pabilo8/ImmersiveIntelligence#95]
ImmersiveEnergy and ImmersiveIntelligence crash on a server if you set a vein size to zero with a NullPointerException in the chunkLoad class 

v. 0.5.4 of IE and v.0.2.0 of II

**Comment by Pabilo8** [comment]
Can't reproduce the issue, it's possible it has been fixed along with another worldgen issues.
