### ISSUE TITLE
[BUG] Ballistic Computer will not Form.

### ISSUE THREAD

**Issue by spiderking23** [Pabilo8/ImmersiveIntelligence#97]
Bug: Hammer and Engineer Hammer do not create Ballistic Computer

To reproduce results:
1. Place all blocks for the Multiblock Structure.
2. Right click on ALL sides with the Engineer's Hammer or Charged Electric hammer.
3. Multiblock structure not formed.

Multiblock Structure: Ballistic Computer Formed

 - Minecraft version: 1.12.2 
 - Forge version: 1.12.2-forge-14.23.5.2854
 - Immersive Intelligence version: 1.12.2-0.1.1
 - Immersive Engineering version: 0.12-98
Other Mods: Immersive Petroleum, Questionably Immersive, Dynamic Trees, Dynamic Trees PHC, JEI, MDXLib, Aliens vs Predator, Mekanism, Music player, U Team core, Serene Seasons, Pamela's Harvest Craft, Better Animals.

**Comment by reimse** [comment]
Dear spiderking23,
Many structures from this mod will not form, because you need to mirror it. it is a Bug...
(i think you have used the projector, right?)

**Comment by S0LiD-ST4T3** [comment]
I have built using the reference in the engineer's manual, and this issue still occurs. could someone give me any troubleshooting tips for the issue before i try to get this issue reopened?

**Comment by reimse** [comment]
The projection is based on the information in the manual. So you have to mirror this too. (Hope I could help...)
