### ISSUE TITLE
[BUG]The Howitzer and the other stuff does not Form

### ISSUE THREAD

**Issue by Stone3006** [Pabilo8/ImmersiveIntelligence#98]
I Charged the hammer and followed the instructions on how to build and activated the howitzer at first I used a projector but it did not work then I tried to manually build it (A lot of times) but it still did not work. Then I tried to make the radio thing and it also does not work the Other stuff does not work too. The machine gun also wont load ammo I kept reading the manual because maybe there was something I was forgetting to do but it was just not working. I hope that you will fix this because this is the only good mod I've found so far that has artillery that has a good mechanics.

**Comment by schafhierte204** [comment]
Please include some pictures, for more specific help ask on discord [https://discord.com/invite/teMfm3R](https://discord.com/invite/teMfm3R)

**Comment by Hawk777** [comment]
Try mirroring. A lot of things from this mod can’t be built mirrored, unlike normal Immersive Engineering. I don’t know whether that’s considered a bug or not.

**Comment by Pabilo8** [comment]
Mirroring issues were fixed in 0.2.0, now almost all multiblocks support flipping (except symmetrical ones like emplacements) and a new NBT-structure based multiblock system was introduced in 0.2.1
